<?php

$popular = [
    'nairobi' => 'Nairobi',
    'nyeri' => 'Nyeri',
    'nakuru' => 'Nakuru',
    'kajiado' => 'Kajiado',
    'laikipia' => 'Laikipia',
    'nyandarua' => 'Nyandarua',
    'kiambu' => 'Kiambu',
    'meru' => 'Meru',
    'kirinyaga' => 'Kirinyaga',
    'narok' => 'Narok',
    'elgeyo_marakwet' => 'Elgeyo-Marakwet',
    'taita_taveta' => 'Taita-Taveta',
    'trans_nzoia' => 'Trans-Nzoia',
    'samburu' => 'Samburu',
];

$other = [
    'baringo' => 'Baringo',
    'bomet' => 'Bomet',
    'bungoma' => 'Bungoma',
    'busia' => 'Busia',
    'embu' => 'Embu',
    'garissa' => 'Garissa',
    'homa_bay' => 'Homa Bay',
    'isiolo' => 'Isiolo',
    'kakamega' => 'Kakamega',
    'kericho' => 'Kericho',
    'kilifi' => 'Kilifi',
    'kisii' => 'Kisii',
    'kisumu' => 'Kisumu',
    'kitui' => 'Kitui',
    'kwale' => 'Kwale',
    'lamu' => 'Lamu',
    'machakos' => 'Machakos',
    'makueni' => 'Makueni',
    'mandera' => 'Mandera',
    'marsabit' => 'Marsabit',
    'migori' => 'Migori',
    'mombasa' => 'Mombasa',
    'muranga' => "Murang'a",
    'nandi' => 'Nandi',
    'nyamira' => 'Nyamira',
    'siaya' => 'Siaya',
    'tana_river' => 'Tana River',
    'tharaka_nithi' => 'Tharaka-Nithi',
    'turkana' => 'Turkana',
    'uasin_gishu' => 'Uasin Gishu',
    'vihiga' => 'Vihiga',
    'wajir' => 'Wajir',
    'west_pokot' => 'West Pokot',
];

return [
    'popular' => $popular,
    'other' => $other,
    'all' => array_merge($popular, $other),
];
